### ISSUE TITLE
Unable to log in to platform

### ISSUE THREAD

**Issue by billyvdinh** [gooddata/gooddata-create-gooddata-react-app#199]
I'm trying to run the demo app, facing an issue says unable to log in to platform.

![image](https://user-images.githubusercontent.com/55896913/195996191-2247553e-aeeb-4ff6-bf47-3facc4dddbae.png)

Anyone here to help me please?

Thanks in advance!

**Comment by support-gooddata-com** [comment]
I believe you are following the steps here: https://sdk.gooddata.com/gooddata-ui/docs/ht_create_your_first_visualization.html. Did you edit package.json while the server was up? If so, the server has to be restarted by following step 4. Always run your local development server using HTTPS because the GoodData API responses set cookies with the secure flag. Specifically, it means that if you skip the HTTPS=true part, you will not be able to log in. It might also be worth checking that your user can log in to the platform.

**Comment by billyvdinh** [comment]
@support-gooddata-com , thanks for your answer!

I can see https://sdk.gooddata.com/gooddata-ui/docs/ht_create_your_first_visualization.html does no longer work. Instead, I created starter app using Accelerator Toolkit, and followed the instruction. I was able to create app and run on local, but can't connect to goodData trial account following `yarn refresh-md` command.

**Comment by jan-r-dev** [comment]
Any chance that your domain/account is configured to allow access via SSO only? In that case, the catalog export would throw this error.

Could you share the name of your domain so that I could verify the log output?
